
package com.scalefocus.tutorials.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Sun Nov 08 16:44:43 CET 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "getServerName", namespace = "http://tutorials.scalefocus.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getServerName", namespace = "http://tutorials.scalefocus.com")

public class GetServerName {


}

