package com.ignyte.whatsshowing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-03T22:42:44.223+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://www.ignyte.com/whatsshowing", name = "MovieInformationSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MovieInformationSoap {

    /**
     * This method will retrieve a list of all movies that are scheduled to be released in the future and their anticipated release dates.
     */
    @WebResult(name = "GetUpcomingMoviesResult", targetNamespace = "http://www.ignyte.com/whatsshowing")
    @RequestWrapper(localName = "GetUpcomingMovies", targetNamespace = "http://www.ignyte.com/whatsshowing", className = "com.ignyte.whatsshowing.GetUpcomingMovies")
    @WebMethod(operationName = "GetUpcomingMovies", action = "http://www.ignyte.com/whatsshowing/GetUpcomingMovies")
    @ResponseWrapper(localName = "GetUpcomingMoviesResponse", targetNamespace = "http://www.ignyte.com/whatsshowing", className = "com.ignyte.whatsshowing.GetUpcomingMoviesResponse")
    public com.ignyte.whatsshowing.ArrayOfUpcomingMovie getUpcomingMovies(
        @WebParam(name = "month", targetNamespace = "http://www.ignyte.com/whatsshowing")
        int month,
        @WebParam(name = "year", targetNamespace = "http://www.ignyte.com/whatsshowing")
        int year
    );

    /**
     * This method will retrieve a list of all theaters and the movies playing today.
     */
    @WebResult(name = "GetTheatersAndMoviesResult", targetNamespace = "http://www.ignyte.com/whatsshowing")
    @RequestWrapper(localName = "GetTheatersAndMovies", targetNamespace = "http://www.ignyte.com/whatsshowing", className = "com.ignyte.whatsshowing.GetTheatersAndMovies")
    @WebMethod(operationName = "GetTheatersAndMovies", action = "http://www.ignyte.com/whatsshowing/GetTheatersAndMovies")
    @ResponseWrapper(localName = "GetTheatersAndMoviesResponse", targetNamespace = "http://www.ignyte.com/whatsshowing", className = "com.ignyte.whatsshowing.GetTheatersAndMoviesResponse")
    public com.ignyte.whatsshowing.ArrayOfTheater getTheatersAndMovies(
        @WebParam(name = "zipCode", targetNamespace = "http://www.ignyte.com/whatsshowing")
        java.lang.String zipCode,
        @WebParam(name = "radius", targetNamespace = "http://www.ignyte.com/whatsshowing")
        int radius
    );
}
