
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ignyte.whatsshowing;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-03T22:42:44.192+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "MovieInformation",
                      portName = "MovieInformationSoap12",
                      targetNamespace = "http://www.ignyte.com/whatsshowing",
                      wsdlLocation = "http://www.ignyte.com/webservices/ignyte.whatsshowing.webservice/moviefunctions.asmx?wsdl",
                      endpointInterface = "com.ignyte.whatsshowing.MovieInformationSoap")
                      
public class MovieInformationSoap12Impl implements MovieInformationSoap {

    private static final Logger LOG = Logger.getLogger(MovieInformationSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.ignyte.whatsshowing.MovieInformationSoap#getUpcomingMovies(int  month ,)int  year )*
     */
    public com.ignyte.whatsshowing.ArrayOfUpcomingMovie getUpcomingMovies(int month,int year) { 
        LOG.info("Executing operation getUpcomingMovies");
        System.out.println(month);
        System.out.println(year);
        try {
            com.ignyte.whatsshowing.ArrayOfUpcomingMovie _return = new com.ignyte.whatsshowing.ArrayOfUpcomingMovie();
            java.util.List<com.ignyte.whatsshowing.UpcomingMovie> _returnUpcomingMovie = new java.util.ArrayList<com.ignyte.whatsshowing.UpcomingMovie>();
            com.ignyte.whatsshowing.UpcomingMovie _returnUpcomingMovieVal1 = new com.ignyte.whatsshowing.UpcomingMovie();
            _returnUpcomingMovieVal1.setMovieName("MovieName-1780545268");
            _returnUpcomingMovie.add(_returnUpcomingMovieVal1);
            _return.getUpcomingMovie().addAll(_returnUpcomingMovie);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ignyte.whatsshowing.MovieInformationSoap#getTheatersAndMovies(java.lang.String  zipCode ,)int  radius )*
     */
    public com.ignyte.whatsshowing.ArrayOfTheater getTheatersAndMovies(java.lang.String zipCode,int radius) { 
        LOG.info("Executing operation getTheatersAndMovies");
        System.out.println(zipCode);
        System.out.println(radius);
        try {
            com.ignyte.whatsshowing.ArrayOfTheater _return = new com.ignyte.whatsshowing.ArrayOfTheater();
            java.util.List<com.ignyte.whatsshowing.Theater> _returnTheater = new java.util.ArrayList<com.ignyte.whatsshowing.Theater>();
            com.ignyte.whatsshowing.Theater _returnTheaterVal1 = new com.ignyte.whatsshowing.Theater();
            _returnTheaterVal1.setName("Name1279854672");
            _returnTheaterVal1.setAddress("Address-658209671");
            com.ignyte.whatsshowing.ArrayOfMovie _returnTheaterVal1Movies = new com.ignyte.whatsshowing.ArrayOfMovie();
            java.util.List<com.ignyte.whatsshowing.Movie> _returnTheaterVal1MoviesMovie = new java.util.ArrayList<com.ignyte.whatsshowing.Movie>();
            _returnTheaterVal1Movies.getMovie().addAll(_returnTheaterVal1MoviesMovie);
            _returnTheaterVal1.setMovies(_returnTheaterVal1Movies);
            _returnTheater.add(_returnTheaterVal1);
            _return.getTheater().addAll(_returnTheater);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
