package com.scalefocus.tutorial;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-15T18:11:46.402+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://tutorial.scalefocus.com", name = "SayHiSecure")
@XmlSeeAlso({ObjectFactory.class})
public interface SayHiSecure {

    @WebResult(name = "textOut", targetNamespace = "")
    @RequestWrapper(localName = "sayHiSecureOperation", targetNamespace = "http://tutorial.scalefocus.com", className = "com.scalefocus.tutorial.SayHiSecureOperation")
    @WebMethod(action = "sayHiSecureAction")
    @ResponseWrapper(localName = "sayHiSecureOperationResponse", targetNamespace = "http://tutorial.scalefocus.com", className = "com.scalefocus.tutorial.SayHiSecureOperationResponse")
    public java.lang.String sayHiSecureOperation(
        @WebParam(name = "sayHiSecurePartIn", targetNamespace = "")
        com.scalefocus.tutorial.GreetingType sayHiSecurePartIn
    );
}
