package com.scalefocus.trainings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-12T08:45:41.194+01:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "UploadFile", 
                  wsdlLocation = "http://localhost:8880/SOAPAttachmentsExampleWS/services/UploadFileServicePort?wsdl",
                  targetNamespace = "http://trainings.scalefocus.com") 
public class UploadFile_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://trainings.scalefocus.com", "UploadFile");
    public final static QName UploadFileServicePort = new QName("http://trainings.scalefocus.com", "UploadFileServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8880/SOAPAttachmentsExampleWS/services/UploadFileServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UploadFile_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8880/SOAPAttachmentsExampleWS/services/UploadFileServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UploadFile_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UploadFile_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadFile_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UploadFile_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UploadFile_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UploadFile_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UploadFileService
     */
    @WebEndpoint(name = "UploadFileServicePort")
    public UploadFileService getUploadFileServicePort() {
        return super.getPort(UploadFileServicePort, UploadFileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadFileService
     */
    @WebEndpoint(name = "UploadFileServicePort")
    public UploadFileService getUploadFileServicePort(WebServiceFeature... features) {
        return super.getPort(UploadFileServicePort, UploadFileService.class, features);
    }

}
