
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scalefocus.trainings;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-12T08:45:41.168+01:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "UploadFile",
                      portName = "UploadFileServicePort",
                      targetNamespace = "http://trainings.scalefocus.com",
                      wsdlLocation = "http://localhost:8880/SOAPAttachmentsExampleWS/services/UploadFileServicePort?wsdl",
                      endpointInterface = "com.scalefocus.trainings.UploadFileService")
                      
public class UploadFileServicePortImpl implements UploadFileService {

    private static final Logger LOG = Logger.getLogger(UploadFileServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scalefocus.trainings.UploadFileService#uploadFile(com.scalefocus.trainings.FileUpload  arg0 )*
     */
    public java.lang.String uploadFile(com.scalefocus.trainings.FileUpload arg0) { 
        LOG.info("Executing operation uploadFile");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1702916579";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
