
package com.scalefocus.trainings;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPMessage;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-12T08:45:41.106+01:00
 * Generated source version: 3.1.3
 * 
 */
public final class UploadFileService_UploadFileServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://trainings.scalefocus.com", "UploadFile");

    private UploadFileService_UploadFileServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UploadFile_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UploadFile_Service ss = new UploadFile_Service(wsdlURL, SERVICE_NAME);
        UploadFileService port = ss.getUploadFileServicePort();  
        Binding bdg = ((BindingProvider) port).getBinding();
        ((javax.xml.ws.soap.SOAPBinding) bdg).setMTOMEnabled(true); 
        
        {
        System.out.println("Invoking uploadFile...");
        com.scalefocus.trainings.FileUpload fileToUpload = new com.scalefocus.trainings.FileUpload();
      
        DataSource fileSource = new FileDataSource(new File("C:/uploads/input/handlers_chains.gif"));
        DataHandler handler = new DataHandler(fileSource);
        
        fileToUpload.setFileData(handler);
        fileToUpload.setFileName("new_uploaded_file");
        fileToUpload.setFileType("gif");
        java.lang.String result = port.uploadFile(fileToUpload);
        System.out.println("uploadFile.result=" + result);


        }

        System.exit(0);
    }

}
