
package net.webservicex.goldsilver;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-04T12:57:59.805+01:00
 * Generated source version: 3.0.4
 * 
 */
public final class LondonGoldAndSilverFixSoap_LondonGoldAndSilverFixSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webservicex.net", "LondonGoldAndSilverFix");

    private LondonGoldAndSilverFixSoap_LondonGoldAndSilverFixSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LondonGoldAndSilverFix.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LondonGoldAndSilverFix ss = new LondonGoldAndSilverFix(wsdlURL, SERVICE_NAME);
        LondonGoldAndSilverFixSoap port = ss.getLondonGoldAndSilverFixSoap();  
        
        {
        System.out.println("Invoking getLondonGoldAndSilverFix...");
        net.webservicex.goldsilver.LondonMarketData _getLondonGoldAndSilverFix__return = port.getLondonGoldAndSilverFix();
        JAXBContext ctx = JAXBContext.newInstance(LondonMarketData.class);
        Marshaller m = ctx.createMarshaller();
        m.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
        m.marshal(_getLondonGoldAndSilverFix__return, System.out);
        //System.out.println("getLondonGoldAndSilverFix.result=" + _getLondonGoldAndSilverFix__return);


        }

        System.exit(0);
    }

}
