package net.webservicex.goldsilver;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-04T12:57:59.883+01:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.webservicex.net", name = "LondonGoldAndSilverFixSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LondonGoldAndSilverFixSoap {

    /**
     * Get London Gold and Silver fixings
     */
    @WebResult(name = "GetLondonGoldAndSilverFixResult", targetNamespace = "http://www.webservicex.net")
    @RequestWrapper(localName = "GetLondonGoldAndSilverFix", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.goldsilver.GetLondonGoldAndSilverFix")
    @WebMethod(operationName = "GetLondonGoldAndSilverFix", action = "http://www.webservicex.net/GetLondonGoldAndSilverFix")
    @ResponseWrapper(localName = "GetLondonGoldAndSilverFixResponse", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.goldsilver.GetLondonGoldAndSilverFixResponse")
    public net.webservicex.goldsilver.LondonMarketData getLondonGoldAndSilverFix();
}
