package net.webservicex.geoipservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-03T23:32:07.358+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "GeoIPService", 
                  wsdlLocation = "file:/C:/prj/WS_workshop/SimpleWebServiceClient/GeoIPService.wsdl",
                  targetNamespace = "http://www.webservicex.net/") 
public class GeoIPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.webservicex.net/", "GeoIPService");
    public final static QName GeoIPServiceSoap = new QName("http://www.webservicex.net/", "GeoIPServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/prj/WS_workshop/SimpleWebServiceClient/GeoIPService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeoIPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/prj/WS_workshop/SimpleWebServiceClient/GeoIPService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeoIPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeoIPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GeoIPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    public GeoIPServiceSoap getGeoIPServiceSoap() {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    public GeoIPServiceSoap getGeoIPServiceSoap(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class, features);
    }

}
