
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex.geoipservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-03T23:32:07.330+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeoIPService",
                      portName = "GeoIPServiceSoap",
                      targetNamespace = "http://www.webservicex.net/",
                      wsdlLocation = "file:/C:/prj/WS_workshop/SimpleWebServiceClient/GeoIPService.wsdl",
                      endpointInterface = "net.webservicex.geoipservice.GeoIPServiceSoap")
                      
public class GeoIPServiceSoapImpl implements GeoIPServiceSoap {

    private static final Logger LOG = Logger.getLogger(GeoIPServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.geoipservice.GeoIPServiceSoap#getGeoIP(java.lang.String  ipAddress )*
     */
    public net.webservicex.geoipservice.GeoIP getGeoIP(java.lang.String ipAddress) { 
        LOG.info("Executing operation getGeoIP");
        System.out.println(ipAddress);
        try {
            net.webservicex.geoipservice.GeoIP _return = new net.webservicex.geoipservice.GeoIP();
            _return.setReturnCode(911700772);
            _return.setIP("IP7315351");
            _return.setReturnCodeDetails("ReturnCodeDetails-714336150");
            _return.setCountryName("CountryName-645388536");
            _return.setCountryCode("CountryCode507386052");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.geoipservice.GeoIPServiceSoap#getGeoIPContext(*
     */
    public net.webservicex.geoipservice.GeoIP getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            net.webservicex.geoipservice.GeoIP _return = new net.webservicex.geoipservice.GeoIP();
            _return.setReturnCode(-705071404);
            _return.setIP("IP-146527233");
            _return.setReturnCodeDetails("ReturnCodeDetails-1534639627");
            _return.setCountryName("CountryName1978513046");
            _return.setCountryCode("CountryCode1985797169");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
